# Site settings
title: "Tales of Murder"
subtitle: "Murder Mystery & Crime Stories ... For readers with time to kill!"
email: contact@talesofmurder.com
description: "A murder mystery short story, novella & novel website. Buy thrilling murder mystery & crime stories to read on any ebook device or app."
logo: /assets/img/site/atticus_fffff0.svg
baseurl: ""
url: "https://www.talesofmurder.com"
repository: "flaturtha/charliechan"

locale: "en_US"

twitter:
  username: "@talesofmurder"

social:
  name: "Rich Cook"
  email: rich@talesofmurder.com
  links:
    - "https://twitter.com/TalesofMurder"
    - "https://www.facebook.com/whoisatticus/"

facebook:
  app_id: 1035153329907183
#   publisher:
#   admins:


# jekyll-json-feed params (https://github.com/snaptortoise/jekyll-json-feeds)
name: "Tales of Murder (name)"


# Read Time is a calculator to provide post Estimated Reading Time (ERT) based on word count. Usage is recommended.
readtime: true
wpm: 200

collections:
  murderwiki:
    output: true
    permalink: /murderwiki/:path/
    title: MurderWiki
  short-stories:
    output: true
    permalink: /short-stories/:path/
    title: Short Stories
  novellas:
    output: true
    permalink: /novellas/:path/
    title: Novellas
  novels:
    output: true
    permalink: /novels/:path/
    title: Novels
  the-red-file:
    output: true
    permalink: /the-red-file/:path/
    title: The Red File
  downloads:
    output: true
    permalink: /your-free-download/:path/
    title: Your Free Download
  landingpages: 
    output: true
    permalink: /:path/
    title: Landing Pages



# paginate: 12
# paginate_path: "/short-stories/page/:num"

# Site Owner
# owner:
#   name: Rich Cook
#   avatar:
#   email: rich@talesofmurder.com
#   google:
#     plus: talesofmurderpress
#     analytics: UA-42672955-1
#     verify:


# Build settings
permalink: /:categories/:title/
markdown: kramdown

gems:
  - jekyll-sitemap
  # - jekyll-seo-tag
  # - jekyll-feed /* doesn't work for collections, only posts; which is STOOPID */

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: ["_pages"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "gulpfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "bower.json"]
# gems: [jekyll-assets, autoprefixer-rails]