# Site settings
title: Tales of Murder
subtitle: For readers with time to kill!
email: contact@talesofmurder.com
description: A murder mystery short story &amp; novel site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.talesofmurder.com" # the base hostname & protocol for your site ... change to "/NOS" for gh-pages
twitter_username: talesofmurder
github_username:  flaturtha
locale: en_US

# Read Time is a calculator to provide post Estimated Reading Time (ERT) based on word count. Usage is recommended.
readtime: true
wpm: 200

collections:
  # bookstore:
  #   output: true
  #   permalink: /bookstore/:path/
  #   title: Bookstore
  murderwiki:
    output: true
    permalink: /murderwiki/:path/
    title: MurderWiki
  short-stories:
    output: true
    permalink: /short-stories/:path/
    title: Short Stories
  novellas:
    output: true
    permalink: /novellas/:path/
    title: Novellas
  novels:
    output: true
    permalink: /novels/:path/
    title: Novels
  the-red-file:
    output: true
    permalink: /the-red-file/:path/
    title: The Red File



# paginate: 12
# paginate_path: "/short-stories/page/:num"

# Site Owner
# owner:
#   name: Rich Cook
#   avatar:
#   email: rich@talesofmurder.com
#   google:
#     plus: talesofmurderpress
#     analytics: UA-42672955-1
#     verify:


# Build settings
permalink: /:categories/:title/
markdown: kramdown

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: ["_pages"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "gulpfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "bower.json"]
# gems: [jekyll-assets, autoprefixer-rails]